spring:
  application:
    name: railway-dislocation
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/alis}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: dislocation
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: dislocation
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/KIS}

server:
  port: ${SERVER_PORT:8090}
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html

webhook:
  secret: ${WEBHOOK_SECRET:}
