CREATE TABLE IF NOT EXISTS etran_invoice (
    id                       UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    waybill_number           VARCHAR(50)  NOT NULL UNIQUE,
    waybill_identifier       VARCHAR(100),
    waybill_status           VARCHAR(100),
    waybill_type             VARCHAR(100),
    shipment_type            VARCHAR(100),
    shipment_speed           VARCHAR(100),
    delivery_deadline        TIMESTAMP,
    waybill_created_at       TIMESTAMP,
    departure_station        VARCHAR(255),
    departure_station_code   VARCHAR(20),
    departure_country        VARCHAR(100),
    destination_station      VARCHAR(255),
    destination_station_code VARCHAR(20),
    destination_country      VARCHAR(100),
    shipper_name             VARCHAR(500),
    shipper_okpo             VARCHAR(20),
    consignee_name           VARCHAR(500),
    consignee_okpo           VARCHAR(20),
    payer                    VARCHAR(500),
    responsible_person       VARCHAR(255),
    etsng_code               VARCHAR(20),
    etsng_name               VARCHAR(255),
    gng_code                 VARCHAR(20),
    cargo_weight             NUMERIC(12, 2),
    cargo_full_name          TEXT,
    raw_json                 JSONB,
    received_at              TIMESTAMP    NOT NULL DEFAULT now(),
    created_at               TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at               TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_etran_invoice_waybill ON etran_invoice(waybill_number);
